name: prana_task2
description: Task 2 udacoding

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: "1.0.0"

dev_dependencies:
  flutter_launcher_icons: "^0.8.0"
  flutter_test:
    sdk: flutter
    
flutter_icons:
  android: true
  ios: true
  image_path: "images/debit-card.png"
  image_path_ios: "images/debit-card.png"
  image_path_android: "images/debit-card.png"
  adaptive_icon_background: "images/debit-card.png"
  adaptive_icon_foreground: "images/debit-card.png"

flutter:

  uses-material-design: true
